# Generated by Django 5.0.4 on 2024-06-03 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "machine_learning",
            "0003_alter_customer_address_alter_customer_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[("Member", "Member"), ("Regular", "Regular")],
                default="Regular",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.CharField(
                choices=[
                    ("0", "0"),
                    ("5", "5"),
                    ("10", "10"),
                    ("15", "15"),
                    ("20", "20"),
                    ("25", "25"),
                    ("30", "30"),
                    ("35", "35"),
                    ("40", "40"),
                    ("45", "45"),
                    ("50", "50"),
                    ("55", "55"),
                    ("60", "60"),
                    ("65", "65"),
                    ("70", "70"),
                    ("75", "75"),
                    ("80", "80"),
                    ("85", "85"),
                    ("90", "90"),
                    ("95", "95"),
                    ("100", "100"),
                ],
                default="0",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("Qris", "Qris"),
                    ("Cash", "Cash"),
                    ("Transfer", "Transfer"),
                    ("Card", "Card"),
                ],
                default="Cash",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="prediction",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="time",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
