# Generated by Django 5.0.4 on 2024-06-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machine_learning", "0006_alter_order_prediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="satisfaction",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
